### ISSUE TITLE
Read private key

### ISSUE THREAD

**Issue by jrootham** [spmjs/grunt-scp#12]
Having a private key hardwired into a gruntfile seems to me to be a really bad idea.  I think you need an option that specifies a key file to read.

**Comment by johnkawakami** [comment]
npmjs.org still has 0.1.8 up there, and the bug that morrissinger fixed is still present.  (How does this get updated?)

I used grunt.file.read() to read in the file. 

    options: {
        privateKey: grunt.file.read('/home/johnk/.ssh/thekeyfilenere'), ...
    }

**Comment by morrissinger** [comment]
@spmjs has to bump the version in package.json and `npm publish` the change.

**Comment by wfairclough** [comment]
@spmjs this still shows version 0.1.8 on npmjs looks like it has not been published yet even though the version has been bumped to 0.1.9

**Comment by dkurucz** [comment]
Sorry for the delay, waiting on permissions to publish to npm.

**Comment by dkurucz** [comment]
I'm not sure your issue will be fixed with 0.1.9 nor 0.1.10, but can you please verify? Current is at 0.1.10

**Comment by wfairclough** [comment]
@dkurucz v0.1.10 is working for me. Thanks!
