### ISSUE TITLE
Configuring without ``cwd`` causes a path.resolve warning

### ISSUE THREAD

**Issue by davidjb** [spmjs/grunt-scp#17]
Using grunt-scp without a ``cwd`` option in the ``files`` configuration produces the following warning:
```
$ grunt -vvv
...
Verifying property scp.upload exists in config...OK
Files: ... -> /opt/data
Options: host="example.org", username="root", password="password"
Warning: Arguments to path.resolve must be strings Use --force to continue.

Aborted due to warnings.
```

I had thought that doing the following with ``src: 'build/*'`` should be okay:
```
        scp: {
            options: {
                host: 'example.org',
                username: 'root',
                password: 'password'
            },
            upload: {
                files: [
                    {src: 'build/*', dest: '/opt/data'}
                ]
            }
        }
```
Seems the issue is https://github.com/spmjs/grunt-scp/blob/master/tasks/scp.js#L81, where ``fileObj.cwd`` and ``fileObj.orig.cwd`` are both undefined.

Using grunt 0.4.5, grunt-scp 0.1.7, npm 1.4.21 and Node v0.10.25.

**Comment by dkurucz** [comment]
this should be resolved with 0.1.10, please reopen if you still have this issue, but also please be aware that without the cwd set to build/ as is currently implemented, based on the supplied configuration, your resulting data structure will be something like /opt/data/build/... unless that is your intention, thanks!
