### ISSUE TITLE
Must I use the 'cwd'?

### ISSUE THREAD

**Issue by muhawo** [spmjs/grunt-scp#28]
When I missed the `cwd` option, I got a error:
> Arguments to path.resolve must be strings Use

And after I add the `cwd` option, the error is gone.

before:
>        scp: {
            options: {
            },
            beta: {
                files: [{
                    src: 'newer/**',
                    filter: 'isFile',
                    dest: '/home/cdn/test'
                }]
            },
        },

after:
>        scp: {
            options: {
            },
            beta: {
                files: [{
                    cwd:'newer',
                    src: '**',
                    filter: 'isFile',
                    dest: '/home/cdn/test'
                }]
            },
        },

**Comment by dkurucz** [comment]
Oh, there is an open pull request that may address this issue.  https://github.com/spmjs/grunt-scp/pull/21

I'll get on testing and merging as soon as possible, sorry for the delay.

**Comment by dkurucz** [comment]
The fix in #21 has been tested and merged
