### ISSUE TITLE
Any chance of supporting a newer version of Grunt?

### ISSUE THREAD

**Issue by kyleramirez** [spmjs/grunt-scp#30]
This module is incredibly useful to me, and I don't want to find an alternative. I'm happy to fork the code myself and help out, if someone can tell me what I need to do.

grunt@0.4.5 is the latest version of Grunt that can be used with this module. That version of Grunt has out-of-date dependencies (graceful-fs@1.2.3), which will be fully deprecated on node releases >= v7.0. Is there a reason why this package has a locked-in peer dependency? Any chance of it being updated for newer versions of Grunt?

**Comment by popomore** [comment]
Seems we can upgrade the latest grunt, then release 1.0 😄

**Comment by dkurucz** [comment]
updated peer dependency, tested on Grunt@1.0.3, seems to be working fine, please let me know if there are issues!

Tagged at 0.1.11
