### ISSUE TITLE
Registering multiple tasks

### ISSUE THREAD

**Issue by augier** [spmjs/grunt-scp#7]
I want to deploy the same file to two different locations: Dev and UAT. So I define a task as such:

```
scp : {
      dev: {
        options : {
          host : 'myip',
          username : 'username',
          password : 'password'
        },
        your_target: {
          files: [{
              cwd: '<% yeoman.exports %>',
              src: 'exports/my.war',
              //filter: 'isFile',
              // path on the server
              dest: '/full/path/to/location/'
          }]
        } 
      }
    }
```

Which doesn't work when I call `scp:dev`

When I remote the dev object and call `scp` it works fine.

Is this an issue or am I using incorrectly?

**Comment by breaklee** [comment]
it's doesn't work. 
scp = {
  dev : {options : {}, upload : {"somethingfiles setting" }},
  live : {}
}

grunt scp:dev:upload;

**Comment by misshula** [comment]
double check your object structure @breaklee 

you have an extra 'upload' there
